services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

    networks:
      - iot-network

    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: temperature-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"

    volumes:
      - mariadb-data:/var/lib/mysql

    networks:
      - iot-network

    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -h localhost -p$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 10
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - iot-network
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped


  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"

    environment:
      - TZ=${TIMEZONE}

    volumes:
      - node-red-data:/data

    networks:
      - iot-network

    restart: unless-stopped
    depends_on:
      - mosquitto
      - mariadb

networks:
  iot-network:
    driver: bridge

volumes:
  mariadb-data:
  node-red-data: