apiVersion: 1
datasources:
  - name: MariaDB
    type: mysql
    uid: mariadb
    url: mariadb:3306
    database: $__env{MYSQL_DATABASE}
    user: $__env{MYSQL_USER}
    secureJsonData:
      password: $__env{MYSQL_PASSWORD}
    isDefault: true
    editable: true
